services:
  h2-database:
    container_name: h2-database
    image: oscarfonts/h2:latest
    volumes:
      - ./h2-data:/opt/h2-data
    ports:
      - "1521:1521"
      - "8080:81"
    environment:
      H2_OPTIONS: -ifNotExists
